name: Build CMFA with Mihomo Smart Core

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 拉取原 ClashMetaForAndroid 仓库最新代码
    - name: Checkout CMFA source
      uses: actions/checkout@v3
      with:
        repository: MetaCubeX/ClashMetaForAndroid
        ref: main
        path: cmfa-source

    # 2. 设置 JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. 设置 Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # 4. 安装 jq 用于解析 JSON
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    # 5. 下载 arm64-v8a smart 内核
    - name: Download latest Mihomo Smart core (arm64-v8a)
      run: |
        ASSETS_BIN_PATH="cmfa-source/app/src/main/jniLibs"
        mkdir -p "$ASSETS_BIN_PATH/arm64-v8a"

        RELEASE_JSON=$(curl -s https://api.github.com/repos/vernesong/mihomo/releases/latest)
        ARM64_URL=$(echo "$RELEASE_JSON" | jq -r '.assets[] | select(.name | test("smart.*android-arm64-v8a")) | .browser_download_url')
        echo "ARM64_URL=$ARM64_URL"

        curl -L -f "$ARM64_URL" -o /tmp/arm64.bin
        if file /tmp/arm64.bin | grep -q "gzip"; then
          gunzip -f /tmp/arm64.bin
          mv /tmp/arm64 "$ASSETS_BIN_PATH/arm64-v8a/mihomo"
        else
          mv /tmp/arm64.bin "$ASSETS_BIN_PATH/arm64-v8a/mihomo"
        fi
        chmod +x "$ASSETS_BIN_PATH/arm64-v8a/mihomo"

        echo "Downloaded and replaced ARM64 smart core successfully!"

    # 6. 构建 APK
    - name: Build APK
      run: |
        cd cmfa-source
        ./gradlew clean assembleRelease

    # 7. 上传 APK 到 Actions Artifact (v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cmfa-smart-apk
        path: cmfa-source/app/build/outputs/apk/release/*.apk
